apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: kuard
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: kuard
    spec:
      containers:
      - name: kuard
        image: gcr.io/kuar-demo/kuard-amd64:1
        ports:
        - containerPort: 8080
        volumeMounts:
          - name: kuard-config
            mountPath: /tmp/kuard-config
          - name: kuard-secret
            mountPath: /tmp/kuard-secret
          - name: kuard-pvc
            mountPath: /tmp/kuard-pvc
        env:
          - name: CONFIG_SOURCE
            valueFrom:
              configMapKeyRef:
                name: kuard-config-env
                key: CONFIG_SOURCE
          - name: FOO
            valueFrom:
              configMapKeyRef:
                name: kuard-config-env
                key: FOO
      volumes:
      - name: kuard-config
        configMap:
          name: kuard-config
      - name: kuard-secret
        secret:
          secretName: kuard-secret
      - name: kuard-pvc
        persistentVolumeClaim:
          claimName: kuard
---
apiVersion: v1
kind: Service
metadata:
  name: kuard
  labels:
    name: kuard
spec:
  type: LoadBalancer
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
  selector:
    app: kuard
---
# Assume using default Storage Class
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: kuard
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kuard-config-env
data:
  CONFIG_SOURCE: yaml
  FOO: bar