apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: elasticsearch
  annotations:
      kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: elasticsearch.13.85.82.216.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: elasticsearch-elasticsearch-client
          servicePort: 9200
  - host: kibana.13.85.82.216.xip.io
    http:
      paths:
      - path: /
        backend:
          serviceName: kibana
          servicePort: 5601
